Updated so that gallery2/install/po and gallery2/upgrade/po put their .mo files into gallery2/locale
git-svn-id: file:///home/jmullan/src/gallery-git/repo/trunk/gallery2@16132 57fcd75e-5312-0410-8df3-f5eb6fbb1595

diff --git a/lib/tools/po/GNUmakefile.inc b/lib/tools/po/GNUmakefile.inc
--- a/lib/tools/po/GNUmakefile.inc
+++ b/lib/tools/po/GNUmakefile.inc
@@ -84,6 +84,13 @@ install: update
 		    exit 1; \
 		fi; \
 		MO_FILE=../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo; \
+            elif test "$(APPLICATION)" = "gallery2_install" \
+	           || test "$(APPLICATION)" = "gallery2_upgrade";  then \
+		if ! $(TOOLDIR)/po/shtool mkdir -p ../../locale/$${LOCALE}/LC_MESSAGES; then \
+		    echo "Could not create directory: ../../locale/$${LOCALE}/LC_MESSAGES"; \
+		    exit 1; \
+		fi; \
+		MO_FILE=../../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo; \
 	    else \
 		MO_FILE=$${LOCALE}.mo; \
 	    fi; \
