Create a new g2data/locale hierarchy and copy all {modules,themes}/*/locale/*/*/*.mo files into that hierarchy when the module is installed. This way we can use a single locale hierarchy for all translations. During the core install, copy the localizations for all installed plugins over to kickstart the process. Simultaneously create support in parallel for putting the .mo files directly into the po directory instead of the per-plugin locale hierarchy.
Bump GalleryCoreApi to 7.20. This change is fully backwards
compatible.

The combination of the above changes means that we can dismantle the
per-plugin locale hierarchies and put all .mo files into the po
directory. Getting rid of this hierarchy will remove as many as
55,000+ directories from svn versions of Gallery (svn 1.3.1 creates as
many as 10 support directories for each dir!). Svn operations should
go much faster. Ftp'ing Gallery2 up to a server will also go much,
much, much, much faster.

Reviews 150 and 158.



git-svn-id: file:///home/jmullan/src/gallery-git/repo/trunk/gallery2@16080 57fcd75e-5312-0410-8df3-f5eb6fbb1595

diff --git a/lib/tools/po/GNUmakefile.inc b/lib/tools/po/GNUmakefile.inc
--- a/lib/tools/po/GNUmakefile.inc
+++ b/lib/tools/po/GNUmakefile.inc
@@ -78,32 +78,36 @@ install: update
 	echo "Updating $(PO)"; \
 	for LOCALE in `ls $(PO).po | grep -v messages.po | sed 's/\.[^.]*$$//g'`; do \
 	    if test -z "$${QUIET}"; then echo $${LOCALE}; fi; \
-	    if $(TOOLDIR)/po/shtool mkdir -p ../locale/$${LOCALE}/LC_MESSAGES; then \
-		php -f $(TOOLDIR)/po/trim-po.php `pwd`/$${LOCALE}.po > tmp.po; \
-		if test "$(OSTYPE)" = "solaris"; then \
-		    if {MSGFMTSOL} ../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo tmp.po; then \
-			if test -n "$${QUIET}"; then \
-			    echo -n '.'; \
-			fi \
-		    else \
-			echo -n "Fail: $${LOCALE}"; \
-			FAIL=1; \
+	    if test -d ../locale; then \
+		if ! $(TOOLDIR)/po/shtool mkdir -p ../locale/$${LOCALE}/LC_MESSAGES; then \
+		    echo "Could not create directory: ../locale/$${LOCALE}/LC_MESSAGES"; \
+		    exit 1; \
+		fi; \
+		MO_FILE=../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo; \
+	    else \
+		MO_FILE=$${LOCALE}.mo; \
+	    fi; \
+	    php -f $(TOOLDIR)/po/trim-po.php `pwd`/$${LOCALE}.po > tmp.po; \
+	    if test "$(OSTYPE)" = "solaris"; then \
+		if {MSGFMTSOL} $${MO_FILE} tmp.po; then \
+		    if test -n "$${QUIET}"; then \
+			echo -n '.'; \
 		    fi \
 		else \
-		    if $(MSGFMT) ../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo tmp.po; then \
-			if test -n "$${QUIET}"; then \
-			    echo -n '.'; \
-			fi \
-		    else \
-			echo -n "Fail: $${LOCALE}"; \
-			FAIL=1; \
-		    fi \
-		fi; \
-		$(RM) tmp.po; \
+		    echo -n "Fail: $${LOCALE}"; \
+		    FAIL=1; \
+		fi \
 	    else \
-		echo "Could not create locale directory for $${LOCALE}."; \
-		FAIL=1; \
+		if $(MSGFMT) $${MO_FILE} tmp.po; then \
+		    if test -n "$${QUIET}"; then \
+			echo -n '.'; \
+		    fi \
+		else \
+		    echo -n "Fail: $${LOCALE}"; \
+		    FAIL=1; \
+		fi \
 	    fi; \
+	    $(RM) tmp.po; \
 	    if test -z "$${QUIET}"; then echo; fi; \
 	done; \
 	if test $${FAIL} -gt 0; then exit 1; fi;
