Rejoice, the new theme system has arrived!  Here's the original proposal: http://marc.theaimsgroup.com/?l=gallery-devel&m=111882332024437&w=2
Highlights of this change:
- Combined layouts and themes into only themes

- All old layouts and themes are gone.  In its place is the Matrix
  theme (which is the old matrix layout + the old matrix theme).  We
  will revive all the other old layouts soon (as themes).

- All page views are delegated to the theme.  There are six different
  types of page views:
    album, photo, admin, module, error, and progress
  The album, photo, error and progress views are generated wholly by
  the theme.  For admin and module views, the framework passes the
  theme a block of template content to wrap nicely.

  - Slideshow, comment, cart, members views are now module views.
  - Comment views are no longer part of ItemAdmin.

- Most of the complex logic has been moved out of the theme into
  "blocks" which are basically reusable Smarty template-based widgets.
  -  You can insert a new block into your template by doing (eg).
      {g->block type="exif.ExifInfo"}
  - Any information that blocks need (from the db, or elsewhere), they
    will load automatically.
  - blocks live in modules/*/templates/blocks and come with a blocks.inc
    file that describes them for the admin UI

- Added callbacks (mechanism that allows blocks to load the data
  it needs).

- Added preloads (mechanism that allows theme to modify the <head>
  element before we start sending content to the browser

- SystemContent is gone, and replaced by blocks

- New admin UI lets you select blocks from a list and add/remove/reorder
  them in a nice DHTML ui.  (Extended settings ui doesn't work properly
  on IE yet).

- Themes now support sidebar, album and photo blocks by default.  This
  means that you can use the UI to say that you want to view comments
  only on album pages, or only on photo pages.  Or both.  Or in the
  sidebar.  The theme designer can allow the user to specify the blocks,
  or the theme designer can hardcode it.

- Totally revamped progress bar mechanism to allow the theme to create
  their own style of progress bar.

- gallery2/templates and everything in it is now gone.  The theme
  controls the whole page.

- main.php considerably simplified

Miscellaneous changes
- Removed obsolete entries from all .po files

- Manifest code now tries to automatically add R entries for you

- PO building code is quieter making it easier to identify errors

- Fixed GPL preamble in all PHP files


git-svn-id: file:///home/jmullan/src/gallery-git/repo/trunk/gallery2@10763 57fcd75e-5312-0410-8df3-f5eb6fbb1595

diff --git a/lib/tools/po/GNUmakefile.inc b/lib/tools/po/GNUmakefile.inc
--- a/lib/tools/po/GNUmakefile.inc
+++ b/lib/tools/po/GNUmakefile.inc
@@ -2,7 +2,7 @@
 # Gallery .mo files makefile
 #
 # This makefile is based on the one provided with the Horde project
-# http://www.horde.org/.  As such, it inherits the license from the 
+# http://www.horde.org/.  As such, it inherits the license from the
 # original version.  You can find that license here:
 #
 # http://cvs.horde.org/co.php/horde/COPYING?r=2.1
@@ -19,10 +19,19 @@
 MODULE_DIR = $(shell dirname `pwd`)
 TYPE_DIR = $(shell dirname $(MODULE_DIR))
 APPLICATION = $(shell basename $(TYPE_DIR))_$(shell basename $(MODULE_DIR))
-MSGFMT = msgfmt --statistics -c -v -o
-MSGFMTSOL = msgfmt -v -o
 
-all: install
+ifdef QUIET
+MSGFMT_FLAGS =
+else
+MSGFMT_FLAGS = -v
+endif
+
+MSGFMT = msgfmt $(MSGFMT_FLAGS) -c -o
+MSGFMTSOL = msgfmt $(MSGFMT_FLAGS) -o
+
+all: update install
+
+all-remove-obsolete: update remove-obsolete install
 
 messages.po:
 	@php -f $(TOOLDIR)/po/extract.php $(MODULE_DIR) $(EXTRA_DIR) > strings.raw
@@ -39,34 +48,47 @@ messages.po:
 clean:
 	@$(RM) messages.po
 
-install: *.po
-	@echo "Checking for os ... ${OSTYPE}"; \
-	if test "${OSTYPE}" = "solaris"; then \
+update: *.po
+
+install:
+	@if test "${OSTYPE}" = "solaris"; then \
 		echo "You'll probably get some warnings on Solaris. This is normal."; \
 	fi; \
+	FAIL=0; \
 	for LOCALE in `ls *.po | sed 's/\.[^.]*$$//g'`; do \
 		if test $${LOCALE}.po = "messages.po"; then \
 			continue; \
 		fi; \
-		echo "Compiling locale $${LOCALE}:"; \
+		if test -z "$${QUIET}"; then echo $${LOCALE}; fi; \
 		if $(TOOLDIR)/po/shtool mkdir -p ../locale/$${LOCALE}/LC_MESSAGES; then \
 			if test "${OSTYPE}" = "solaris"; then \
 				if {MSGFMTSOL} ../locale/$${LOCALE}/LC_MESSAGES/${APPLICATION}.mo $${LOCALE}.po; then \
-					echo; \
+					if test ! -z "$${QUIET}"; then \
+						echo -n '.'; \
+					fi \
 				else \
-					echo "  ... FAILED"; \
-					echo; \
+					echo -n "Fail: $${LOCALE}"; \
+					FAIL=1; \
 				fi \
 			else \
 				if ${MSGFMT} ../locale/$${LOCALE}/LC_MESSAGES/${APPLICATION}.mo $${LOCALE}.po; then \
-					echo; \
+					if test ! -z "$${QUIET}"; then \
+						echo -n '.'; \
+					fi \
 				else \
-					echo "  ... FAILED"; \
-					echo; \
-                                        exit 1; \
+					echo -n "Fail: $${LOCALE}"; \
+					FAIL=1; \
 				fi \
 			fi; \
 		else \
 			echo "Could not create locale directory for $${LOCALE}."; \
-		fi \
+		fi; \
+		if test -z "$${QUIET}"; then echo; fi; \
+	done; \
+	if test $${FAIL} -gt 0; then exit 1; fi;
+	@echo '';
+
+remove-obsolete:
+	@for LOCALE in `ls *.po | egrep -v messages.po | sed 's/\.[^.]*$$//g'`; do \
+		msgattrib --no-obsolete --output-file=$${LOCALE}.po $${LOCALE}; \
 	done;
